#spring:
#  redis:
#    database:
#      0
#    host:
#      39.97.64.30
#    jedis:
#      pool:
#        max-act:
#          8
#        max-idle:
#          8
#        max-wait:
#          -1ms
#        min-idle:
#          0